image: hseeberger/scala-sbt:11.0.14.1_1.6.2_3.1.1

cache:
  paths:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: none
  SBT_OPTS: '-Xmx2g -Xss10m -Xms1g'

stages:
  - validate
  - publish

Run Tests:
  stage: validate
  script: sbt +test:compile
  except:
    - main
    - tags

Check formatting:
  stage: validate
  script:
    - sbt -v scalafmtCheckAll
  except:
    - main
    - tags

Release next version:
  stage: publish
  only:
    - main
  script:
    - gpg --batch --yes --import $GPG_SIGNING_KEY
    - gpg --list-keys
    - apt update && apt install --no-install-recommends -y dnsutils netcat-openbsd
    - mkdir ~/.ssh
    - set -xe
    - ssh-keyscan -H -p 22 gitlab.com > ~/.ssh/known_hosts
    - cp $SSH_DEPLOY_PRIVATE_KEY_PATH ~/.ssh/id_rsa
    - chmod 0400 ~/.ssh/*
    - git config user.name "Gitlab CI"
    - git config user.email $GITLAB_USER_EMAIL
    - git checkout $CI_COMMIT_REF_NAME
    - git remote set-url --push origin $(perl -pe 's#.*@(.+?(\:\d+)?)/#git@\1:#' <<< $CI_REPOSITORY_URL)
    - git config --list
    - cp $SONATYPE_CONFIG sonatype-creds.sbt
    - sbt -v "release with-defaults"
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /\[no release\]/
      - $CI_COMMIT_MESSAGE =~ /\[release commit\]/

Publish release:
  stage: publish
  script:
    - gpg --batch --yes --import $GPG_SIGNING_KEY
    - gpg --list-keys
    - cp $SONATYPE_CONFIG sonatype-creds.sbt
    - sbt -v ";+publishSigned;sonatypeBundleRelease"
  only:
    - tags
